In [1]:
import pandas as pd
from matplotlib.pyplot import *
import numpy as np
from scipy.interpolate import *
from scipy.stats import *


In [3]:
yl=['FY97','FY98','FY99','FY00','FY01','FY02','FY03','FY04','FY05','FY06','FY07','FY08','FY09','FY10','FY11','FY12','FY13','FY14','FY15','FY16']

In [4]:
finaltotal=[]
noimmi=np.array([])

In [5]:
for ls in yl:
    immixls=pd.read_excel('/Users/militbetai/Desktop/733 Project/FYs97-16_NIVDetailTable.xls',sheetname=ls,skiprows=230,parse_cols='CL')
    finaltotal.append(immixls)

In [7]:
listvalues=[]
for i in range(0,20):
    a = list(finaltotal[i].columns.values)
    listvalues.append(a)
print listvalues

[[5942061], [5814153], [6192478], [7141636], [7588778], [5769437], [4881634], [5049099], [5388951], [5836730], [6444285], [6603076], [5804182], [6422751], [7507939], [8927090], [9164349], [9932480], [10891745], [10381491]]


In [8]:
noimmi = np.array(listvalues)
print noimmi[0], yl[0]
years=[1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016]

[5942061] FY97


In [9]:
total=[]
for i in range(0,20):
    a=noimmi[i,0]
    total.append(a)
    
np.array(total)
print total

[5942061, 5814153, 6192478, 7141636, 7588778, 5769437, 4881634, 5049099, 5388951, 5836730, 6444285, 6603076, 5804182, 6422751, 7507939, 8927090, 9164349, 9932480, 10891745, 10381491]


In [10]:
years=pd.Series(years)
noimmi=pd.Series(total)

In [11]:
len(years)

20

In [12]:
len(total)

20

In [13]:
noimmi=np.array(noimmi)
print noimmi

[ 5942061  5814153  6192478  7141636  7588778  5769437  4881634  5049099
  5388951  5836730  6444285  6603076  5804182  6422751  7507939  8927090
  9164349  9932480 10891745 10381491]


In [14]:
years=np.array(years)
print years

[1997 1998 1999 2000 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011
 2012 2013 2014 2015 2016]


In [15]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets, linear_model

In [16]:
Y_train=noimmi
len(Y_train)
Y_train=np.reshape(Y_train,(20,1))
Y_train.shape
print Y_train

[[ 5942061]
 [ 5814153]
 [ 6192478]
 [ 7141636]
 [ 7588778]
 [ 5769437]
 [ 4881634]
 [ 5049099]
 [ 5388951]
 [ 5836730]
 [ 6444285]
 [ 6603076]
 [ 5804182]
 [ 6422751]
 [ 7507939]
 [ 8927090]
 [ 9164349]
 [ 9932480]
 [10891745]
 [10381491]]


In [17]:
X_train=years
len(years)
X_train=np.reshape(X_train,(20,1))
print X_train
X_train.shape

[[1997]
 [1998]
 [1999]
 [2000]
 [2001]
 [2002]
 [2003]
 [2004]
 [2005]
 [2006]
 [2007]
 [2008]
 [2009]
 [2010]
 [2011]
 [2012]
 [2013]
 [2014]
 [2015]
 [2016]]


(20, 1)

In [18]:
regr = linear_model.LinearRegression()

In [19]:
regr.fit(X_train, Y_train)
print X_train, Y_train

[[1997]
 [1998]
 [1999]
 [2000]
 [2001]
 [2002]
 [2003]
 [2004]
 [2005]
 [2006]
 [2007]
 [2008]
 [2009]
 [2010]
 [2011]
 [2012]
 [2013]
 [2014]
 [2015]
 [2016]] [[ 5942061]
 [ 5814153]
 [ 6192478]
 [ 7141636]
 [ 7588778]
 [ 5769437]
 [ 4881634]
 [ 5049099]
 [ 5388951]
 [ 5836730]
 [ 6444285]
 [ 6603076]
 [ 5804182]
 [ 6422751]
 [ 7507939]
 [ 8927090]
 [ 9164349]
 [ 9932480]
 [10891745]
 [10381491]]


In [20]:
regr.predict(2017)

array([[ 9470359.19999999]])

In [21]:
%matplotlib inline
regr.predict(2018)

array([[ 9697610.81428576]])

In [22]:
regr.predict(2019)

array([[ 9924862.42857146]])