In [6]:
import pandas as pd
from matplotlib.pyplot import *
from scipy.interpolate import *
from scipy.stats import *
import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets, linear_model

In [7]:
finaltotal=[]
noimmi=np.array([])

In [8]:
top=pd.read_excel('/Users/militbetai/Desktop/733 Project/FYs97-16_NIVDetailTable.xls',sheetname='TOP')

In [9]:
top
in_list=[]
gbr_list=[]
ja_list=[]
ch_list=[]
me_list=[]
sk_list=[]
year_list=[]
for i in range (0,20):
    x=top['INDIA'][i]
    in_list.append(x)

for i in range (0,20):
    x1=top['GBR'][i]
    gbr_list.append(x1)
    
for i in range (0,20):    
    x2=top['JAPAN'][i]
    ja_list.append(x2)
    
for i in range (0,20):    
    x3=top['SOUTH KOREA'][i]
    sk_list.append(x3)
    
for i in range (0,20):    
    x4=top['MEXICO'][i]
    me_list.append(x4)
    
for i in range (0,20):    
    x5=top['CHINA'][i]
    ch_list.append(x5)
    
for i in range (0,20):    
    x6=top['YEARS'][i]
    year_list.append(x6)    

In [11]:
in_list

[31684,
 40246,
 55062,
 61530,
 74078,
 44012,
 42245,
 63737,
 53579,
 64887,
 83464,
 72517,
 55886,
 58664,
 72438,
 80630,
 99705,
 108817,
 119952,
 126692]

In [12]:
india=np.array(in_list)
in_train=np.reshape(india,(20,1))
in_train

year=np.array(year_list)
year_train=np.reshape(year,(20,1))
year_train

gbr=np.array(gbr_list)
gbr_train=np.reshape(gbr,(20,1))

sk=np.array(sk_list)
sk_train=np.reshape(sk,(20,1))

ja=np.array(ja_list)
ja_train=np.reshape(ja,(20,1))

ch=np.array(ch_list)
ch_train=np.reshape(ch,(20,1))

me=np.array(me_list)
me_train=np.reshape(me,(20,1))

In [13]:
india, year

(array([ 31684,  40246,  55062,  61530,  74078,  44012,  42245,  63737,
         53579,  64887,  83464,  72517,  55886,  58664,  72438,  80630,
         99705, 108817, 119952, 126692]),
 array([1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007,
        2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016]))

In [14]:
regr = linear_model.LinearRegression()

In [15]:
regr.fit(year_train, sk_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [16]:

regr.predict(2019)

array([[ 3669.56992481]])